--Creacion de la funcion de auditor
DELETE FROM funciones_roles WHERE fncod ='album_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='album_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='album_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Album'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='artist_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='artist_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='artist_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Artist'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='bitacora_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='bitacora_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='bitacora_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Bitacora'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='carretilla_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='carretilla_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='carretilla_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Carretilla'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Carretillaanon'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='favorites_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='favorites_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='favorites_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Favorites'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='funciones_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='funciones_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='funciones_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funciones'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funcionesroles'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='genre_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='genre_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='genre_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Genre'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='highligths_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='highligths_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='highligths_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligths'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligthsplaylist'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='log_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='log_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='log_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Log'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Lognonuser'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='loguser_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='loguser_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='loguser_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Loguser'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='offer_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='offer_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='offer_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offer'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offersubscription'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='playlist_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='playlist_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='playlist_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlist'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlistsongs'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='popularity_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='popularity_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='popularity_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Popularity'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='products_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='products_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='products_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Products'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='purchase_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='purchase_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='purchase_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Purchase'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Purchasedetail'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='roles_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='roles_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='roles_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Roles'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Rolesusuarios'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='song_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='song_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='song_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Song'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='songauthors_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='songauthors_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='songauthors_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Songauthors'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='subscription_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='subscription_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='subscription_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscription'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscriptionuser'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='usuario_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='usuario_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='usuario_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Usuario'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='video_UPD' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='video_INS' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='video_DEL' AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='Menu_Video'AND rolescod = 'AUDIT';
DELETE FROM funciones_roles WHERE fncod ='album_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='album_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='album_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Album'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Albums\\Albums' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Albums\\Album' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='artist_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='artist_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='artist_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Artist'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Artists\\Artists' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Artists\\Artist' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='bitacora_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='bitacora_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='bitacora_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Bitacora'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Bitacoras\\Bitacoras' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Bitacoras\\Bitacora' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funciones_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funciones_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funciones_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funciones'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Funcioness\\Funcioness' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Funcioness\\Funciones' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funcionesroles'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Funcionesroless\\Funcionesroless' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Funcionesroless\\Funcionesroles' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='genre_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='genre_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='genre_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Genre'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Genres\\Genres' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Genres\\Genre' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligths_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligths_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligths_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligths'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Highligthss\\Highligthss' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Highligthss\\Highligths' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligthsplaylist'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Highligthsplaylists\\Highligthsplaylists' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Highligthsplaylists\\Highligthsplaylist' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='log_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='log_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='log_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Log'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Logs\\Logs' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Logs\\Log' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Lognonuser'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Lognonusers\\Lognonusers' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Lognonusers\\Lognonuser' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='loguser_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='loguser_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='loguser_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Loguser'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Logusers\\Logusers' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Logusers\\Loguser' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='offer_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='offer_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='offer_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offer'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Offers\\Offers' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Offers\\Offer' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='playlist_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='playlist_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='playlist_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlist'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Playlists\\Playlists' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Playlists\\Playlist' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlistsongs'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Playlistsongss\\Playlistsongss' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Playlistsongss\\Playlistsongs' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='popularity_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='popularity_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='popularity_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Popularity'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Popularitys\\Popularitys' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Popularitys\\Popularity' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='roles_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='roles_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='roles_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Roles'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Roless\\Roless' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Roless\\Roles' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Rolesusuarios'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Rolesusuarioss\\Rolesusuarioss' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Rolesusuarioss\\Rolesusuarios' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='song_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='song_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='song_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Song'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Songs\\Songs' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Songs\\Song' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='songauthors_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='songauthors_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='songauthors_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Songauthors'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Songauthorss\\Songauthorss' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Songauthorss\\Songauthors' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='subscription_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='subscription_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='subscription_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscription'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Subscriptions\\Subscriptions' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Subscriptions\\Subscription' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='usuario_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='usuario_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='usuario_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Usuario'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Usuarios\\Usuarios' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Usuarios\\Usuario' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='video_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='video_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='video_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Video'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Videos\\Videos' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Videos\\Video' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Admin\\Dashboard' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Escupitajo\\GenerarCrud' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='bitacora_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='bitacora_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='bitacora_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Bitacora'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funciones_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funciones_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funciones_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funciones'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funcionesroles'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligths_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligths_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligths_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligths'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligthsplaylist'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='log_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='log_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='log_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Log'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Lognonuser'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='loguser_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='loguser_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='loguser_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Loguser'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='offer_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='offer_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='offer_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offer'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='roles_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='roles_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='roles_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Roles'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Rolesusuarios'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='subscription_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='subscription_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='subscription_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscription'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='usuario_UPD' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='usuario_INS' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='usuario_DEL' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Menu_Usuario'AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Admin\\Dashboard' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Escupitajo\\GenerarCrud' AND rolescod = 'CLN';
DELETE FROM funciones_roles WHERE fncod ='album_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='album_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='album_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Album'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='artist_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='artist_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='artist_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Artist'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='bitacora_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='bitacora_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='bitacora_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Bitacora'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretilla_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretilla_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretilla_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Carretilla'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Carretillaanon'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='favorites_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='favorites_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='favorites_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Favorites'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funciones_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funciones_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funciones_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funciones'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funcionesroles'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='genre_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='genre_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='genre_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Genre'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligths_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligths_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligths_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligths'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligthsplaylist'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='log_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='log_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='log_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Log'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Lognonuser'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='loguser_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='loguser_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='loguser_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Loguser'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offer_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offer_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offer_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offer'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offersubscription'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlist_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlist_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlist_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlist'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlistsongs'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='popularity_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='popularity_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='popularity_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Popularity'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='products_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='products_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='products_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Products'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchase_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchase_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchase_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Purchase'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Purchasedetail'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='roles_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='roles_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='roles_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Roles'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Rolesusuarios'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='song_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='song_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='song_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Song'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='songauthors_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='songauthors_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='songauthors_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Songauthors'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscription_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscription_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscription_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscription'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscriptionuser'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='usuario_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='usuario_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='usuario_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Usuario'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='video_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='video_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='video_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Video'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='album_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='album_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='album_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Album'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='artist_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='artist_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='artist_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Artist'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='bitacora_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='bitacora_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='bitacora_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Bitacora'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretilla_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretilla_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretilla_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Carretilla'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='carretillaanon_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Carretillaanon'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='favorites_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='favorites_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='favorites_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Favorites'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funciones_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funciones_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funciones_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funciones'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='funcionesroles_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Funcionesroles'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='genre_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='genre_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='genre_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Genre'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligths_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligths_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligths_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligths'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='highligthsplaylist_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Highligthsplaylist'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='log_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='log_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='log_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Log'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='lognonuser_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Lognonuser'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='loguser_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='loguser_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='loguser_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Loguser'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offer_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offer_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offer_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offer'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='offersubscription_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Offersubscription'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlist_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlist_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlist_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlist'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='playlistsongs_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Playlistsongs'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='popularity_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='popularity_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='popularity_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Popularity'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='products_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='products_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='products_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Products'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchase_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchase_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchase_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Purchase'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='purchasedetail_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Purchasedetail'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='roles_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='roles_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='roles_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Roles'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='rolesusuarios_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Rolesusuarios'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='song_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='song_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='song_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Song'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='songauthors_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='songauthors_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='songauthors_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Songauthors'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscription_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscription_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscription_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscription'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='subscriptionuser_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Subscriptionuser'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='usuario_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='usuario_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='usuario_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Usuario'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='video_UPD' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='video_INS' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='video_DEL' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Menu_Video'AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Admin\\Dashboard' AND rolescod = 'INV';
DELETE FROM funciones_roles WHERE fncod ='Controllers\\Escupitajo\\GenerarCrud' AND rolescod = 'INV';
